#!/bin/bash

export HOST=mysql-marinesrecipes.alwaysdata.net
export DB_NAME=marinesrecipes_bd
export DB_USER=201428
export DB_PASSWORD=Luka-12021996

export HOST_LOCAL=localhost
export PORT_LOCAL=8889
export DB_NAME_LOCAL=marinesrecipes_bd
export DB_USER_LOCAL=root
export DB_PASSWORD_LOCAL=root

export AUTH_CLIENT=680726405067-3gam69kea82fcsu8al0ff3kuqcaengtl.apps.googleusercontent.com
export AUTH_CLIENT_PASSWORD=qiusRaX7DaloMdhQMiAB0lwD
export AUTH_URL=https://developers.google.com/oauthplayground

export AUTH_USER=marinesrecipes@gmail.com
export AUTH_CLIENT_ID=680726405067-3gam69kea82fcsu8al0ff3kuqcaengtl.apps.googleusercontent.com
export AUTH_CLIENT_PASSWORD=qiusRaX7DaloMdhQMiAB0lwD
export AUTH_REFRESH_TOKEN=1//04pWeER_VOvN4CgYIARAAGAQSNwF-L9Ir2Oa64ZVrBw5LQCqO-Vbj90ow7m7EhXSm6Bk1XtSyyeoaO76viFcm3vdbp2aWIe7SCQM